version: '3.8'

services:
  web:
    build: .
#    command: gunicorn social_media.wsgi:application --bind 0.0.0.0:8000 --reload
    command: sleep infinity
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db

volumes:
  postgres_data: