# Generated by Django 4.2.13 on 2024-07-06 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_postcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcomment",
            options={"ordering": ("-created_at",)},
        ),
    ]
